"""extend audit log for administration module

Revision ID: 107095967769
Revises: 742f03778de9
Create Date: 2026-08-13 15:09:30.831435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107095967769'
down_revision: Union[str, Sequence[str], None] = '742f03778de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SETTINGS_TABLE = sa.table(
    "system_settings",
    sa.column("key", sa.String),
    sa.column("value", sa.String),
    sa.column("description", sa.String),
)

# App config (not demo data) — seeded via the migration itself, same pattern as every prior
# module's settings. String-valued display/company settings, not numeric thresholds.
ADMINISTRATION_SETTINGS = [
    {"key": "company_name", "value": "OG-PIOS",
     "description": "Company/organization name shown in report headers and the application chrome."},
    {"key": "default_currency", "value": "USD",
     "description": "Default currency for new cost/revenue entries where none is otherwise specified. One of: USD, NGN."},
    {"key": "unit_system", "value": "imperial",
     "description": "Default unit system for display. One of: imperial, metric."},
    {"key": "date_format", "value": "YYYY-MM-DD",
     "description": "Preferred date display format."},
    {"key": "timezone", "value": "UTC",
     "description": "Default timezone for displaying timestamps."},
    {"key": "default_production_unit", "value": "bopd",
     "description": "Default unit label for oil production rates."},
    {"key": "default_gas_unit", "value": "mscfd",
     "description": "Default unit label for gas production rates."},
    {"key": "default_volume_unit", "value": "bbl",
     "description": "Default unit label for oil/liquid volumes."},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('status', sa.String(length=20), nullable=False, server_default='success'))
    op.add_column('audit_logs', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    # NOTE: autogenerate proposed dropping uq_commodity_prices_commodity_date here — a false
    # positive, the same recurring class hit in every migration since Production Loss. That
    # constraint was hand-added via op.create_unique_constraint rather than declared in the
    # CommodityPrice model's __table_args__, so autogenerate's model-vs-DB diff doesn't
    # recognize it as "belonging" to the model. It must never be dropped.
    # ### end Alembic commands ###

    op.bulk_insert(SETTINGS_TABLE, ADMINISTRATION_SETTINGS)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DELETE FROM system_settings WHERE key IN ("
        + ", ".join(f"'{row['key']}'" for row in ADMINISTRATION_SETTINGS)
        + ")"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_column('audit_logs', 'metadata_json')
    op.drop_column('audit_logs', 'status')
    # ### end Alembic commands ###
