"""add missing indexes on hot-path FK and status columns

Revision ID: 2fe36c589f73
Revises: a9e7334bdb53
Create Date: 2026-08-16 13:03:50.265961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe36c589f73'
down_revision: Union[str, Sequence[str], None] = 'a9e7334bdb53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate proposed dropping uq_commodity_prices_commodity_date here — a
    # recurring false positive (see every migration since Production Loss). That constraint was
    # hand-added via op.create_unique_constraint rather than declared in the CommodityPrice
    # model's __table_args__, so autogenerate's model-vs-DB diff doesn't recognize it as
    # "belonging" to the model. It must never be dropped.

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_recommendations_equipment_id'), 'ai_recommendations', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_facility_id'), 'ai_recommendations', ['facility_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_field_id'), 'ai_recommendations', ['field_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_well_id'), 'ai_recommendations', ['well_id'], unique=False)
    op.create_index(op.f('ix_alerts_equipment_id'), 'alerts', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_alerts_facility_id'), 'alerts', ['facility_id'], unique=False)
    op.create_index(op.f('ix_alerts_field_id'), 'alerts', ['field_id'], unique=False)
    op.create_index(op.f('ix_alerts_well_id'), 'alerts', ['well_id'], unique=False)
    op.create_index(op.f('ix_equipment_facility_id'), 'equipment', ['facility_id'], unique=False)
    op.create_index(op.f('ix_equipment_status'), 'equipment', ['status'], unique=False)
    op.create_index(op.f('ix_equipment_well_id'), 'equipment', ['well_id'], unique=False)
    op.create_index(op.f('ix_equipment_readings_equipment_id'), 'equipment_readings', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_equipment_id'), 'maintenance_records', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_operating_costs_equipment_id'), 'operating_costs', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_operating_costs_facility_id'), 'operating_costs', ['facility_id'], unique=False)
    op.create_index(op.f('ix_operating_costs_field_id'), 'operating_costs', ['field_id'], unique=False)
    op.create_index(op.f('ix_operating_costs_well_id'), 'operating_costs', ['well_id'], unique=False)
    op.create_index(op.f('ix_production_losses_equipment_id'), 'production_losses', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_production_losses_well_id'), 'production_losses', ['well_id'], unique=False)
    op.create_index(op.f('ix_wells_status'), 'wells', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wells_status'), table_name='wells')
    op.drop_index(op.f('ix_production_losses_well_id'), table_name='production_losses')
    op.drop_index(op.f('ix_production_losses_equipment_id'), table_name='production_losses')
    op.drop_index(op.f('ix_operating_costs_well_id'), table_name='operating_costs')
    op.drop_index(op.f('ix_operating_costs_field_id'), table_name='operating_costs')
    op.drop_index(op.f('ix_operating_costs_facility_id'), table_name='operating_costs')
    op.drop_index(op.f('ix_operating_costs_equipment_id'), table_name='operating_costs')
    op.drop_index(op.f('ix_maintenance_records_equipment_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_equipment_readings_equipment_id'), table_name='equipment_readings')
    op.drop_index(op.f('ix_equipment_well_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_status'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_facility_id'), table_name='equipment')
    op.drop_index(op.f('ix_alerts_well_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_field_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_facility_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_equipment_id'), table_name='alerts')
    op.drop_index(op.f('ix_ai_recommendations_well_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_field_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_facility_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_equipment_id'), table_name='ai_recommendations')
    # ### end Alembic commands ###
