"""add equipment info fields

Revision ID: 3b9c217baa6d
Revises: 8876892ab81c
Create Date: 2026-08-09 19:44:18.577798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9c217baa6d'
down_revision: Union[str, Sequence[str], None] = '8876892ab81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('equipment', sa.Column('commissioning_date', sa.Date(), nullable=True))
    op.add_column('equipment', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('equipment', sa.Column('operating_hours', sa.Float(), nullable=True))
    op.add_column('equipment', sa.Column('next_maintenance_due', sa.Date(), nullable=True))
    # ### end Alembic commands ###

    # App config (not demo data) — must exist in every environment, same reasoning as
    # boe_gas_factor_scf_per_bbl in the previous migration.
    op.bulk_insert(
        sa.table(
            "system_settings",
            sa.column("key", sa.String),
            sa.column("value", sa.String),
            sa.column("description", sa.String),
        ),
        [
            {
                "key": "equipment_health_operating_hours_threshold",
                "value": "40000",
                "description": (
                    "Operating hours above which the equipment health score starts "
                    "deducting points for equipment age/wear."
                ),
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'next_maintenance_due')
    op.drop_column('equipment', 'operating_hours')
    op.drop_column('equipment', 'description')
    op.drop_column('equipment', 'commissioning_date')
    op.drop_column('equipment', 'name')
    # ### end Alembic commands ###
