"""add well completion fields

Revision ID: 408beac6a9ce
Revises: 50843f289d70
Create Date: 2026-08-09 16:18:22.484947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408beac6a9ce'
down_revision: Union[str, Sequence[str], None] = '50843f289d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wells', sa.Column('completion_date', sa.Date(), nullable=True))
    op.add_column('wells', sa.Column('completion_type', sa.String(length=100), nullable=True))
    op.add_column('wells', sa.Column('total_depth_ft', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wells', 'total_depth_ft')
    op.drop_column('wells', 'completion_type')
    op.drop_column('wells', 'completion_date')
    # ### end Alembic commands ###
