"""add ai interpretation field to insight model

Revision ID: 709cc3909898
Revises: fea98f807a60
Create Date: 2026-08-10 19:55:46.316620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709cc3909898'
down_revision: Union[str, Sequence[str], None] = 'fea98f807a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_recommendations', sa.Column('ai_interpretation', sa.Text(), nullable=True))
    # NOTE: autogenerate proposes dropping uq_commodity_prices_commodity_date here — the same
    # recurring false positive hit in every migration since Production Loss (hand-added
    # constraint, not declared in the model's __table_args__). Must never be dropped.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_recommendations', 'ai_interpretation')
    # ### end Alembic commands ###
