"""extend report model for reports module

Revision ID: 742f03778de9
Revises: f2a150e1c63d
Create Date: 2026-08-11 14:25:19.762665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742f03778de9'
down_revision: Union[str, Sequence[str], None] = 'f2a150e1c63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate proposed dropping uq_commodity_prices_commodity_date here — a false
    # positive, the same recurring class hit in every migration since Production Loss. That
    # constraint was hand-added via op.create_unique_constraint rather than declared in the
    # CommodityPrice model's __table_args__, so autogenerate's model-vs-DB diff doesn't
    # recognize it as "belonging" to the model. It must never be dropped.
    op.add_column('reports', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('reports', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('filters', sa.JSON(), nullable=False))
    op.add_column('reports', sa.Column('sections', sa.JSON(), nullable=False))
    op.add_column('reports', sa.Column('results', sa.JSON(), nullable=True))
    op.add_column('reports', sa.Column('calculation_version', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('reports', 'generated_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'generated_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('reports', 'last_generated_at')
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'calculation_version')
    op.drop_column('reports', 'results')
    op.drop_column('reports', 'sections')
    op.drop_column('reports', 'filters')
    op.drop_column('reports', 'description')
    op.drop_column('reports', 'name')
    # ### end Alembic commands ###
