"""add production targets, system settings, and record-date uniqueness

Revision ID: 8876892ab81c
Revises: 408beac6a9ce
Create Date: 2026-08-09 17:24:29.434239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8876892ab81c'
down_revision: Union[str, Sequence[str], None] = '408beac6a9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('production_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('oil_target_bopd', sa.Float(), nullable=True),
    sa.Column('gas_target_mscfd', sa.Float(), nullable=True),
    sa.Column('water_target_bwpd', sa.Float(), nullable=True),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('well_id', 'effective_date', name='uq_production_targets_well_date')
    )
    op.create_index(op.f('ix_production_targets_effective_date'), 'production_targets', ['effective_date'], unique=False)
    op.create_unique_constraint('uq_pressure_records_well_date', 'pressure_records', ['well_id', 'record_date'])
    op.create_unique_constraint('uq_production_records_well_date', 'production_records', ['well_id', 'record_date'])
    op.create_unique_constraint('uq_temperature_records_well_date', 'temperature_records', ['well_id', 'record_date'])
    # ### end Alembic commands ###

    # Default app config (not demo data) — must exist in every environment, so it's
    # seeded here rather than in backend/app/db/seed_wells.py.
    op.bulk_insert(
        sa.table(
            "system_settings",
            sa.column("key", sa.String),
            sa.column("value", sa.String),
            sa.column("description", sa.String),
        ),
        [
            {
                "key": "boe_gas_factor_scf_per_bbl",
                "value": "6000",
                "description": (
                    "Standard cubic feet of gas per barrel-of-oil-equivalent, used to "
                    "compute BOE (gas_mscfd * 1000 / factor)."
                ),
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_temperature_records_well_date', 'temperature_records', type_='unique')
    op.drop_constraint('uq_production_records_well_date', 'production_records', type_='unique')
    op.drop_constraint('uq_pressure_records_well_date', 'pressure_records', type_='unique')
    op.drop_index(op.f('ix_production_targets_effective_date'), table_name='production_targets')
    op.drop_table('production_targets')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
