"""extend alert model and add status history

Revision ID: 904e02efa718
Revises: 3b65bf411ca3
Create Date: 2026-08-10 13:36:43.669373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904e02efa718'
down_revision: Union[str, Sequence[str], None] = '3b65bf411ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SETTINGS_TABLE = sa.table(
    "system_settings",
    sa.column("key", sa.String),
    sa.column("value", sa.String),
    sa.column("description", sa.String),
)

# App config (not demo data) — seeded via the migration itself, same pattern as
# maintenance_schedule_lookahead_days. Defaults documented in docs/data-model.md's Alerts rule
# table.
ALERT_THRESHOLD_SETTINGS = [
    {"key": "alert_production_below_target_pct", "value": "10",
     "description": "Percent below target production that triggers a Production Below Target alert."},
    {"key": "alert_production_decline_pct", "value": "15",
     "description": "Percent decline of trailing 7-day vs. trailing 30-day average oil production that triggers a Production Decline alert."},
    {"key": "alert_production_unusual_change_pct", "value": "30",
     "description": "Percent day-over-day oil production swing (either direction) that triggers an Unusual Production Change alert."},
    {"key": "alert_equipment_health_attention_threshold", "value": "50",
     "description": "Equipment health score below this (and at/above the critical threshold) triggers a Low Equipment Health alert."},
    {"key": "alert_equipment_health_critical_threshold", "value": "25",
     "description": "Equipment health score below this triggers a Critical Equipment Health alert."},
    {"key": "alert_maintenance_repeated_events_count", "value": "3",
     "description": "Number of corrective/emergency maintenance events within the repeated-events window that triggers a Repeated Maintenance Events alert."},
    {"key": "alert_maintenance_repeated_events_window_days", "value": "90",
     "description": "Trailing window (days) used to count repeated maintenance events per equipment."},
    {"key": "alert_production_loss_high_threshold_bbl", "value": "50",
     "description": "Estimated barrels lost on a single production-loss event that triggers a High Production Loss alert."},
    {"key": "alert_production_loss_repeated_events_count", "value": "3",
     "description": "Number of production-loss events within the repeated-events window that triggers a Repeated Production-Loss Events alert."},
    {"key": "alert_production_loss_repeated_events_window_days", "value": "90",
     "description": "Trailing window (days) used to count repeated production-loss events per well."},
    {"key": "alert_downtime_high_threshold_hours", "value": "24",
     "description": "Downtime hours on a single production-loss event that triggers a High Downtime alert."},
    {"key": "alert_high_lost_revenue_threshold_usd", "value": "10000",
     "description": "Estimated USD revenue impact on a single production-loss event that triggers a High Estimated Lost Revenue alert."},
    {"key": "alert_high_operating_cost_threshold_usd", "value": "100000",
     "description": "USD operating cost total for a field this period that triggers a High Operating Cost alert."},
    {"key": "alert_high_operating_cost_threshold_ngn", "value": "50000000",
     "description": "NGN operating cost total for a field this period that triggers a High Operating Cost alert."},
    {"key": "alert_cost_per_bbl_increase_pct", "value": "20",
     "description": "Percent month-over-month increase in a field's cost per barrel that triggers a Rising Cost per Barrel alert."},
    {"key": "alert_cost_per_boe_increase_pct", "value": "20",
     "description": "Percent month-over-month increase in a field's cost per BOE that triggers a Rising Cost per BOE alert."},
    {"key": "alert_margin_decline_pct", "value": "25",
     "description": "Percent month-over-month decline in a field's estimated operating margin that triggers a Declining Operating Margin alert."},
    {"key": "alert_high_maintenance_cost_multiplier", "value": "2.0",
     "description": "Multiple of the fleet's trailing-90-day average maintenance cost that triggers a High Maintenance Cost alert for one equipment item."},
    {"key": "alert_high_financial_impact_threshold_usd", "value": "25000",
     "description": "Trailing-30-day summed USD estimated production-loss revenue impact for a field that triggers a High Estimated Financial Impact alert."},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=20), nullable=True),
    sa.Column('to_state', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_status_history_alert_id'), 'alert_status_history', ['alert_id'], unique=False)
    op.add_column('alerts', sa.Column('category', sa.String(length=30), nullable=False))
    op.add_column('alerts', sa.Column('source_module', sa.String(length=50), nullable=False))
    op.add_column('alerts', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('alerts', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('alerts', sa.Column('recommended_action', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('field_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('facility_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('maintenance_record_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('production_loss_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('threshold_value', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('current_value', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('alerts', sa.Column('dedup_key', sa.String(length=300), nullable=False))
    op.add_column('alerts', sa.Column('occurrence_count', sa.Integer(), nullable=False))
    op.add_column('alerts', sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_by_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_state'), 'alerts', ['state'], unique=False)
    op.create_foreign_key('fk_alerts_resolved_by_id', 'alerts', 'users', ['resolved_by_id'], ['id'])
    op.create_foreign_key('fk_alerts_maintenance_record_id', 'alerts', 'maintenance_records', ['maintenance_record_id'], ['id'])
    op.create_foreign_key('fk_alerts_acknowledged_by_id', 'alerts', 'users', ['acknowledged_by_id'], ['id'])
    op.create_foreign_key('fk_alerts_field_id', 'alerts', 'fields', ['field_id'], ['id'])
    op.create_foreign_key('fk_alerts_facility_id', 'alerts', 'facilities', ['facility_id'], ['id'])
    op.create_foreign_key('fk_alerts_production_loss_id', 'alerts', 'production_losses', ['production_loss_id'], ['id'])
    op.drop_column('alerts', 'message')
    # NOTE: autogenerate proposes dropping uq_commodity_prices_commodity_date here — a false
    # positive. That constraint was hand-added via op.create_unique_constraint in the
    # Production Loss module's migration (9ec63324886e) rather than declared in the
    # CommodityPrice model's __table_args__, so autogenerate's model-vs-DB diff doesn't
    # recognize it as "belonging" to the model. It must never be dropped — same recurring
    # false-positive class hit in every migration since Production Loss.
    # ### end Alembic commands ###

    op.bulk_insert(SETTINGS_TABLE, ALERT_THRESHOLD_SETTINGS)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DELETE FROM system_settings WHERE key IN ("
        + ", ".join(f"'{row['key']}'" for row in ALERT_THRESHOLD_SETTINGS)
        + ")"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_alerts_resolved_by_id', 'alerts', type_='foreignkey')
    op.drop_constraint('fk_alerts_maintenance_record_id', 'alerts', type_='foreignkey')
    op.drop_constraint('fk_alerts_acknowledged_by_id', 'alerts', type_='foreignkey')
    op.drop_constraint('fk_alerts_field_id', 'alerts', type_='foreignkey')
    op.drop_constraint('fk_alerts_facility_id', 'alerts', type_='foreignkey')
    op.drop_constraint('fk_alerts_production_loss_id', 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_state'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_column('alerts', 'resolved_by_id')
    op.drop_column('alerts', 'acknowledged_by_id')
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'acknowledged_at')
    op.drop_column('alerts', 'last_detected_at')
    op.drop_column('alerts', 'occurrence_count')
    op.drop_column('alerts', 'dedup_key')
    op.drop_column('alerts', 'unit')
    op.drop_column('alerts', 'current_value')
    op.drop_column('alerts', 'threshold_value')
    op.drop_column('alerts', 'production_loss_id')
    op.drop_column('alerts', 'maintenance_record_id')
    op.drop_column('alerts', 'facility_id')
    op.drop_column('alerts', 'field_id')
    op.drop_column('alerts', 'notes')
    op.drop_column('alerts', 'recommended_action')
    op.drop_column('alerts', 'description')
    op.drop_column('alerts', 'title')
    op.drop_column('alerts', 'source_module')
    op.drop_column('alerts', 'category')
    op.drop_index(op.f('ix_alert_status_history_alert_id'), table_name='alert_status_history')
    op.drop_table('alert_status_history')
    # ### end Alembic commands ###
