"""add scenario model for what-if simulator

Revision ID: f2a150e1c63d
Revises: 709cc3909898
Create Date: 2026-08-11 10:36:19.825499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a150e1c63d'
down_revision: Union[str, Sequence[str], None] = '709cc3909898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SETTINGS_TABLE = sa.table(
    "system_settings",
    sa.column("key", sa.String),
    sa.column("value", sa.String),
    sa.column("description", sa.String),
)

# App config (not demo data) — seeded via the migration itself, same pattern as every prior
# module's threshold settings.
WHATIF_THRESHOLD_SETTINGS = [
    {"key": "whatif_reasonable_change_pct_bound", "value": "50",
     "description": "Absolute percent change beyond which a What-If Simulator assumption is still computed but flagged as outside configured operating assumptions."},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('baseline_date_from', sa.Date(), nullable=False),
    sa.Column('baseline_date_to', sa.Date(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('calculation_version', sa.String(length=20), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate proposed dropping uq_commodity_prices_commodity_date here — a false
    # positive, the same recurring class hit in every migration since Production Loss. That
    # constraint was hand-added via op.create_unique_constraint rather than declared in the
    # CommodityPrice model's __table_args__, so autogenerate's model-vs-DB diff doesn't
    # recognize it as "belonging" to the model. It must never be dropped.
    # ### end Alembic commands ###

    op.bulk_insert(SETTINGS_TABLE, WHATIF_THRESHOLD_SETTINGS)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DELETE FROM system_settings WHERE key IN ("
        + ", ".join(f"'{row['key']}'" for row in WHATIF_THRESHOLD_SETTINGS)
        + ")"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenarios')
    # ### end Alembic commands ###
