"""extend ai recommendation into insight model and add evidence feedback tables

Revision ID: fea98f807a60
Revises: 904e02efa718
Create Date: 2026-08-10 17:25:38.156297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea98f807a60'
down_revision: Union[str, Sequence[str], None] = '904e02efa718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SETTINGS_TABLE = sa.table(
    "system_settings",
    sa.column("key", sa.String),
    sa.column("value", sa.String),
    sa.column("description", sa.String),
)

# App config (not demo data) — seeded via the migration itself, same pattern as every prior
# module's threshold settings.
INSIGHT_THRESHOLD_SETTINGS = [
    {"key": "insight_production_increase_pct", "value": "15",
     "description": "Percent increase in production (trailing 7-day vs. 30-day average) that triggers a Production Increase insight."},
    {"key": "insight_trend_window_months", "value": "3",
     "description": "Number of months of monthly production totals used to classify a well's Production Trend insight."},
    {"key": "insight_well_comparison_ratio_threshold", "value": "0.6",
     "description": "A well producing below this fraction of its field's median oil rate is flagged in the Well Performance Comparison insight."},
    {"key": "insight_maintenance_frequency_increase_multiplier", "value": "1.5",
     "description": "Multiple of the prior-window maintenance event count that triggers an Increasing Maintenance Frequency insight."},
    {"key": "insight_high_maintenance_cost_vs_production_threshold_usd", "value": "5",
     "description": "USD maintenance cost per barrel of oil that triggers a High Maintenance Cost vs. Production insight."},
    {"key": "insight_cross_domain_lookback_days", "value": "90",
     "description": "Trailing window (days) used to gather supplementary maintenance/downtime evidence for cross-domain insights."},
    {"key": "insight_stale_after_days", "value": "7",
     "description": "Days since an insight was last reaffirmed by the engine before it is flagged stale in the API/UI."},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insight_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_label', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['ai_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insight_evidence_insight_id'), 'ai_insight_evidence', ['insight_id'], unique=False)
    op.create_table('ai_insight_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['ai_recommendations.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insight_feedback_insight_id'), 'ai_insight_feedback', ['insight_id'], unique=False)
    op.add_column('ai_recommendations', sa.Column('insight_type', sa.String(length=100), nullable=False))
    op.add_column('ai_recommendations', sa.Column('category', sa.String(length=30), nullable=False))
    op.add_column('ai_recommendations', sa.Column('severity', sa.String(length=20), nullable=False))
    op.add_column('ai_recommendations', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('ai_recommendations', sa.Column('generated_by', sa.String(length=20), nullable=False))
    op.add_column('ai_recommendations', sa.Column('ai_provider', sa.String(length=50), nullable=True))
    op.add_column('ai_recommendations', sa.Column('ai_model', sa.String(length=100), nullable=True))
    op.add_column('ai_recommendations', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('ai_recommendations', sa.Column('summary', sa.Text(), nullable=False))
    op.add_column('ai_recommendations', sa.Column('data_quality_note', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('confidence_level', sa.String(length=10), nullable=False))
    op.add_column('ai_recommendations', sa.Column('estimated_production_impact_value', sa.Float(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('estimated_production_impact_unit', sa.String(length=20), nullable=True))
    op.add_column('ai_recommendations', sa.Column('estimated_production_impact_note', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('estimated_financial_impact_value', sa.Float(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('estimated_financial_impact_currency', sa.String(length=10), nullable=True))
    op.add_column('ai_recommendations', sa.Column('estimated_financial_impact_note', sa.Text(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('field_id', sa.Integer(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('facility_id', sa.Integer(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('maintenance_record_id', sa.Integer(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('production_loss_id', sa.Integer(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('alert_id', sa.Integer(), nullable=True))
    op.add_column('ai_recommendations', sa.Column('dedup_key', sa.String(length=300), nullable=False))
    op.add_column('ai_recommendations', sa.Column('occurrence_count', sa.Integer(), nullable=False))
    op.add_column('ai_recommendations', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('ai_recommendations', sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_ai_recommendations_category'), 'ai_recommendations', ['category'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_dedup_key'), 'ai_recommendations', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_insight_type'), 'ai_recommendations', ['insight_type'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_severity'), 'ai_recommendations', ['severity'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_status'), 'ai_recommendations', ['status'], unique=False)
    op.drop_constraint(op.f('ai_recommendations_ai_prediction_id_fkey'), 'ai_recommendations', type_='foreignkey')
    op.create_foreign_key('fk_ai_recommendations_maintenance_record_id', 'ai_recommendations', 'maintenance_records', ['maintenance_record_id'], ['id'])
    op.create_foreign_key('fk_ai_recommendations_production_loss_id', 'ai_recommendations', 'production_losses', ['production_loss_id'], ['id'])
    op.create_foreign_key('fk_ai_recommendations_field_id', 'ai_recommendations', 'fields', ['field_id'], ['id'])
    op.create_foreign_key('fk_ai_recommendations_alert_id', 'ai_recommendations', 'alerts', ['alert_id'], ['id'])
    op.create_foreign_key('fk_ai_recommendations_facility_id', 'ai_recommendations', 'facilities', ['facility_id'], ['id'])
    op.drop_column('ai_recommendations', 'confidence')
    op.drop_column('ai_recommendations', 'ai_prediction_id')
    op.drop_column('ai_recommendations', 'evidence')
    op.drop_column('ai_recommendations', 'observation')
    op.drop_column('ai_recommendations', 'possible_contributors')
    op.drop_column('ai_recommendations', 'potential_impact')
    # NOTE: autogenerate proposes dropping uq_commodity_prices_commodity_date here — a false
    # positive, same recurring class hit in every migration since Production Loss. That
    # constraint was hand-added via op.create_unique_constraint rather than declared in the
    # CommodityPrice model's __table_args__, so autogenerate's model-vs-DB diff doesn't
    # recognize it as "belonging" to the model. It must never be dropped.
    # ### end Alembic commands ###

    op.bulk_insert(SETTINGS_TABLE, INSIGHT_THRESHOLD_SETTINGS)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DELETE FROM system_settings WHERE key IN ("
        + ", ".join(f"'{row['key']}'" for row in INSIGHT_THRESHOLD_SETTINGS)
        + ")"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_recommendations', sa.Column('potential_impact', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_recommendations', sa.Column('possible_contributors', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_recommendations', sa.Column('observation', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('ai_recommendations', sa.Column('evidence', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_recommendations', sa.Column('ai_prediction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_recommendations', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint('fk_ai_recommendations_maintenance_record_id', 'ai_recommendations', type_='foreignkey')
    op.drop_constraint('fk_ai_recommendations_production_loss_id', 'ai_recommendations', type_='foreignkey')
    op.drop_constraint('fk_ai_recommendations_field_id', 'ai_recommendations', type_='foreignkey')
    op.drop_constraint('fk_ai_recommendations_alert_id', 'ai_recommendations', type_='foreignkey')
    op.drop_constraint('fk_ai_recommendations_facility_id', 'ai_recommendations', type_='foreignkey')
    op.create_foreign_key(op.f('ai_recommendations_ai_prediction_id_fkey'), 'ai_recommendations', 'ai_predictions', ['ai_prediction_id'], ['id'])
    op.drop_index(op.f('ix_ai_recommendations_status'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_severity'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_insight_type'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_dedup_key'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_category'), table_name='ai_recommendations')
    op.drop_column('ai_recommendations', 'severity')
    op.drop_column('ai_recommendations', 'last_confirmed_at')
    op.drop_column('ai_recommendations', 'generated_at')
    op.drop_column('ai_recommendations', 'occurrence_count')
    op.drop_column('ai_recommendations', 'dedup_key')
    op.drop_column('ai_recommendations', 'alert_id')
    op.drop_column('ai_recommendations', 'production_loss_id')
    op.drop_column('ai_recommendations', 'maintenance_record_id')
    op.drop_column('ai_recommendations', 'facility_id')
    op.drop_column('ai_recommendations', 'field_id')
    op.drop_column('ai_recommendations', 'estimated_financial_impact_note')
    op.drop_column('ai_recommendations', 'estimated_financial_impact_currency')
    op.drop_column('ai_recommendations', 'estimated_financial_impact_value')
    op.drop_column('ai_recommendations', 'estimated_production_impact_note')
    op.drop_column('ai_recommendations', 'estimated_production_impact_unit')
    op.drop_column('ai_recommendations', 'estimated_production_impact_value')
    op.drop_column('ai_recommendations', 'confidence_level')
    op.drop_column('ai_recommendations', 'data_quality_note')
    op.drop_column('ai_recommendations', 'summary')
    op.drop_column('ai_recommendations', 'title')
    op.drop_column('ai_recommendations', 'ai_model')
    op.drop_column('ai_recommendations', 'ai_provider')
    op.drop_column('ai_recommendations', 'generated_by')
    op.drop_column('ai_recommendations', 'status')
    op.drop_column('ai_recommendations', 'category')
    op.drop_column('ai_recommendations', 'insight_type')
    op.drop_index(op.f('ix_ai_insight_feedback_insight_id'), table_name='ai_insight_feedback')
    op.drop_table('ai_insight_feedback')
    op.drop_index(op.f('ix_ai_insight_evidence_insight_id'), table_name='ai_insight_evidence')
    op.drop_table('ai_insight_evidence')
    # ### end Alembic commands ###
